improve installer script and make the service remain after exit

diff --git a/meta-leda-components/recipes-sdv/eclipse-leda/files/airgap-container-installer b/meta-leda-components/recipes-sdv/eclipse-leda/files/airgap-container-installer
--- a/meta-leda-components/recipes-sdv/eclipse-leda/files/airgap-container-installer
+++ b/meta-leda-components/recipes-sdv/eclipse-leda/files/airgap-container-installer
@@ -28,22 +28,22 @@ fi
 if [ ! -d "${tar_dir}" ]; then
     echo "${tar_dir} either does not exist or is not a directory"
     exit 1
-fi 
+fi
 
 if [ -z "$(ls -A ${tar_dir}/*.tar* 2>/dev/null)" ]; then
-   echo "Nothing to install"
-   exit 0
+    echo "Nothing to install"
+    exit 0
 fi
 
 # ctr image import is very slow even when importing the same image twice
 # we keep a list of already imported images and we skip them
 LOCK_PATH="${tar_dir}/${IMPORTED_CTRS_LOCK_NAME}"
-if [ -f "$LOCK_PATH" ]; then
+if [ ! -f ${LOCK_PATH} ]; then
     echo "Lock at ${LOCK_PATH} does not exist. Creating an empty lock."
-    touch $LOCK_PATH
+    echo "# THIS FILE KEEPS A LOG OF ALL IMAGES ALREADY IMPORTED BY AIRGAP-CONTAINER-INSTALLER.SERVICE" >>${LOCK_PATH}
+    echo "# DELETE ANY LINES FOR IMAGES THAT YOU WISH TO BE RE-IMPORTED ON SERVICE RESTART" >>${LOCK_PATH}
     echo "Created ${LOCK_PATH}"
 fi
-
 
 for tar_image in "${tar_dir}"/*.tar*; do
     echo "Loading ${tar_image}..."
@@ -51,11 +51,17 @@ for tar_image in "${tar_dir}"/*.tar*; do
     if grep -Fxq "$tar_base_name" ${LOCK_PATH}; then
         # Container image already imported, skipping...
         echo "Already imported...Skipping"
-        continue;
+        continue
     else
         echo "Importing new image"
-        ctr --namespace kanto-cm image import ${tar_image} --no-unpack || exit $?
-        echo "${tar_base_name}" >> ${LOCK_PATH}
-        echo "Imported"
-    fi    
+        import_msg=$(ctr --namespace kanto-cm image import ${tar_image} --no-unpack)
+        import_rc=$?
+        if [ $import_rc -eq 0 ]; then
+            echo "${tar_base_name}" >>${LOCK_PATH}
+            echo "Imported"
+        else
+            echo "Importing ${tar_image} failed with message: ${import_msg}, rc: ${import_rc}"
+            continue
+        fi
+    fi
 done
